name: wesource
markdown: redcarpet
permalink: /:year/:month/:title/
url: http://wesource.se/
#url: http://127.0.0.1:4000/
author:
    name: Henric Hedin
    twitter: #henrichedin
    
twitter_username: henrichedin
github_username:  wesource    
    
#highlighter: rouge
highlighter: pygments
